### ISSUE TITLE
SpeckleCore.SpecklePlaceholder instead of List(int)

### ISSUE THREAD

**Issue by alfonsomonedero** [speckleworks/SpeckleCore#113]
#### Expected Behaviour
I feed a list in integers in Grasshopper with repeated numbers. What I should receive on Dynamo is the List(int)

#### Actual Behaviour
Every time an integer is repeated in the List, speckle is substituting it with SpeckleCore.SpecklePlaceholder. In principle is great as it reduces the data online, but it fails in the de-serialisation. 

![image](https://user-images.githubusercontent.com/43339587/55096165-4646f680-50b1-11e9-814c-9cfb59fff331.png)

![image](https://user-images.githubusercontent.com/43339587/55096080-257ea100-50b1-11e9-83c9-02213fe7bf8a.png)

**Comment by didimitrie** [comment]
hm, so both gh and dynamo ignore duplicate values? damn. i can reproduce it:

![image](https://user-images.githubusercontent.com/7696515/55096476-ebfa6580-50b1-11e9-9806-ebf3a88c0677.png)

but there is a workaround (at least for gh, i think possibly dynamo too):

![image](https://user-images.githubusercontent.com/7696515/55096572-164c2300-50b2-11e9-98aa-34a3ec41beeb.png)

using the "create speckle object" component + encapsulate list, you get rid of this behaviour. On the other side you'll need to expand speckle object in gh. Dynamo I believe should handle the dictionaries easier... 

I've flagged this as a bug and will get to it asap!

**Comment by MrAlex8** [comment]
Any advice for when this happens going from dynamo to grasshopper?

**Comment by didimitrie** [comment]
So, after a couple of months, this is finally fixed - for the brave, you can get the pre release from here: https://github.com/speckleworks/SpeckleInstaller/releases/tag/v1.4.0
