### ISSUE TITLE
Duplicate objects not allowed, regardless of ownership 

### ISSUE THREAD

**Issue by tluth** [speckleworks/SpeckleCore#140]
Step 0: 
- [x ] I've  read the [contribution guidelines](https://github.com/speckleworks/SpeckleOrg/blob/master/CONTRIBUTING.md)!
#### Expected Behaviour
2 users should be able to make streams with identical object lists 

#### Actual Behaviour
Second user who tries to create a stream and upload objects will find that no new objects are created and the objects shown in their stream are actually owned by the first user. 

#### Reproduction Steps & System Config (win, osx, web, etc.)
create 2 streams full of identical stuff from 2 different users. Here's a basic example of the python code I was using:
```
def new_stream(name, description=''):
    url = "https://{}/api/streams".format(os.environ["SERVER"])
    payload = {"name": name, "description": description}
    r = requests.post(url, data=json.dumps(payload), headers=headers)
    return r.json()

""" send dummy data to speckle stream """
stream = new_stream(name, description)
stream_id = stream["resource"]["streamId"]
print(stream_id)
url = "https://{}/api/streams/{}".format(os.environ["SERVER"], stream_id)
with open("./dummy_data.json") as f: 
    objects = json.load(f)["resources"]
payload = {"objects": objects}
r = requests.put(url, data=json.dumps(payload), headers=headers)   
```

#### Proposed Solution (if any)
I get that this helps avoid redundancy, but I feel like there's realistic cases where 2 users might wanna work on the same data. 'lowit

**Comment by didimitrie** [comment]
Not sure what’s the problem? Object ownership is not enforced, only stream ownership - so the second user can still have his own (private or not) stream with identical objects. 

Unless i’m missing something 👀

**Comment by tluth** [comment]
So i uploaded some test data to a new account, which had previously been uploaded on another account. But the new account wasn't able to update the objects in the new stream

**Comment by tluth** [comment]
This whole thing of mongo db referencing old objects when creating new similar objects is still being super annoying.. And if this can happen across accounts then I don't know how you're supposed to deal with this.

**Comment by tluth** [comment]
closing because it belongs more in speckle server
