### ISSUE TITLE
Add color property to speckleobject

### ISSUE THREAD

**Issue by PaulPoinet** [speckleworks/SpeckleCore#15]
byObject, byLayer?

**Comment by didimitrie** [comment]
Will be just a generic "colour" property:
- If not null, set colour from that
- If null or not present, set it from object's layer

**Comment by PaulPoinet** [comment]
what about byMaterial xD?
Also, .TextColor for textdot would be nice (.Color being the background one)

**Comment by didimitrie** [comment]
Yep, and from memory:
- All speckle objects will have a f¢ colour property, which can stay null 
- SpeckleAnnotation will extend that with, say `backgroundColor` - because we need to keep things readable. 

Any thoughts on Linear dimensions and other stuff like this? I loathe them

**Comment by PaulPoinet** [comment]
For Linear dimensions, if you want I can start to create a SpeckleLinearDimension (or however you want to call it) based on this: http://developer.rhino3d.com/api/RhinoCommon/html/M_Rhino_Geometry_LinearDimension__ctor_1.htm

But I have no idea how it would be constructed in other platforms (Revit, etc.), no not sure how to make something properly generic.
Other objects to look at in Rhino are also Hashes and Lights

**Comment by didimitrie** [comment]
Think these will go into props by default, and application logic will need to handle this going fwd. Won't change base schemas now...
