### ISSUE TITLE
Same mongo ID for different curves that share very similar topology

### ISSUE THREAD

**Issue by PaulPoinet** [speckleworks/SpeckleCore#2]
<img width="977" alt="capture" src="https://user-images.githubusercontent.com/22736626/30177362-e48278e8-9405-11e7-8f3b-59609ba99f9d.PNG">

Might be problematic for offset curves...

**Comment by didimitrie** [comment]
in here https://github.com/speckleworks/SpeckleCore/blob/master/SpeckleCore/BaseObjectsExtensions.cs

the polyline hash fails to deliver... need to serialise that array before passing it, like for meshes

**Comment by PaulPoinet** [comment]
We should send `Rhino.DocObjects.CurveObject.CurveGeometry` instead of `Rhino.DocObjects.CurveObject`. The latter is interpreted as a string. Hence the bug/confusion.
