### ISSUE TITLE
Handling exceptions for retrieving UserDictionaries

### ISSUE THREAD

**Issue by PaulPoinet** [speckleworks/SpeckleCore#3]
Concerning the future SpeckleRhino interface, I noticed that there is no code written to handle ToNurbsCurve() conversions (in order to retrieve the UserDictionary), like it is done for the Grasshopper component here:
https://github.com/speckleworks/SpeckleUserDataUtils/blob/dev/SetUserDataComponent.cs#L67-L74

Therefore I propose to add the same conversion here (I am not sure if this is consistent): 

<img width="505" alt="tonurbscurve" src="https://user-images.githubusercontent.com/22736626/30250870-4ff913f0-9656-11e7-95e6-15e6312f6781.PNG">

**Comment by PaulPoinet** [comment]
I tested that on my computer and works alright

**Comment by didimitrie** [comment]
Okay this seems to be an issue for https://github.com/speckleworks/SpeckleRhinoConverter.
