### ISSUE TITLE
Converter does not support tuples

### ISSUE THREAD

**Issue by didimitrie** [speckleworks/SpeckleCore#40]
Essentially, he freaks out and does not serialise them.

**Comment by didimitrie** [comment]
Ok, I figured how to serialise them. Deserialising them is though a pain, as are all other "generic type" objects...

**Comment by tsvilans** [comment]
Fair... seems to be a bag of worms. I'm trying out something new to get rid of using Tuples anyway, using a simple class / struct instead.

**Comment by tsvilans** [comment]
Since it seems to serialize simple classes and such easily, anyway.

**Comment by didimitrie** [comment]
I have to check structs, good shout!

**Comment by didimitrie** [comment]
Structs work nicely. My advice is to yes, avoid using dynamic types and/or stuff with generic arguments. There are some costly workarounds that I'll look into. Until then, I think best is to replace your tuples with structs or some simple classes...

Todos: 
- [ ] KeyValuePairs`n (dynamic objects)
- [ ] Tuples`n (...)

**Comment by didimitrie** [comment]
I'm actually going to close this one for now, too much work for potentially fickle and dangerous functionality...

**Comment by tsvilans** [comment]
No worries from me. My new stuff doesn't use Tuples anymore.
