### ISSUE TITLE
Create local cache of streams

### ISSUE THREAD

**Issue by fraguada** [speckleworks/SpeckleCore#42]
To make things snappier and nice fallback for offline. Would be nice to have a 'make available offline' sort of functionality.

**Comment by didimitrie** [comment]
This is kind-of fixed now in the https://github.com/speckleworks/SpeckleCore/tree/Dimitrie/dev/localdb-sqlite branch. It improves massively receiver performance, as well as senders - no more huge refresh on a fresh file open. 

Will get closed when we do the big update.
