### ISSUE TITLE
SpeckleAbstract: Include namespace in object _type & add another search by object type before shallow deconversion

### ISSUE THREAD

**Issue by didimitrie** [speckleworks/SpeckleCore#55]
This would allow for objects to be deserialised to native types even if the assembly name differs, as the case might be when producing libraries for various applications that don't share a `core` lib

**Comment by radumg** [comment]
@didimitrie , not uber-familiar with how you handle deserialisation (catching up with things) but i can't find a mention of `TypeNameHandling.All` in the repo, is adding `_type` a similar solution to what this option in the Newtonsoft does ?

**Comment by didimitrie** [comment]
It's layered and probs the not the most efficient way, but it explicitly works nicely and the exposure to devs is cool.  

Flow:
`Native Object -> SpeckleObject -> Json -> Payload -> Server -> hopefully db`

Native Object -> SpeckleObject:
- either via an extension called ToSpeckle/ToNative if one is present in the app domain
- to speckleAbstract if native object is serialisable

`_type` just keeps track in speckle abstract objects of where they come from and what's their name, together with  `assembly`.  It's not complete, but have a look at https://speckle.works/blog/schemasandstandards/

This issue is partially fixed in @jmirtsch 's  branch... which i have to check, and with whom i'm chatting atm too, so  it's all very confusing

**Comment by jmirtsch** [comment]
This is probably something I can help mock up, at least turning a speckle line into a grid or something given I've already done this on a more advanced level.  https://twitter.com/geometrygym/status/969998398752423943  How the user nominates that a line represents a grid, a model line or something else in a revit project needs some thought (sounds like you might have some ideas on this @archinate .  My external implementation uses the IFC data model to nominate purpose and other parameters etc.

**Comment by didimitrie** [comment]
This has been partly addressed on the https://github.com/speckleworks/SpeckleCore/tree/Dimitrie/dev/localdb-sqlite branch, as now if no exact match was found (assembly name *and* version), it will search just by assembly name. 

So even if there's different libs, we can ask devs to use the same assembly name between them, otherwise the `SpeckleAbstract` type gets messy.
