### ISSUE TITLE
Project Number

### ISSUE THREAD

**Issue by Eckart-S** [speckleworks/SpeckleCore#67]
Add project number please - this is often used together with the name.

**Comment by didimitrie** [comment]
todo: 
- mod specs SpeckleSpecs
- rebuild docs
- update schema in SpeckleServer
- add project number prop in SpeckleCore

**Comment by Eckart-S** [comment]
Any news on this?
Required for professional office work in many offices.

**Comment by mswaidan** [comment]
@didimitrie is there a way to automatically update the schema in SpeckleServer? I've got the new .yaml loaded in swagger and see the generate server button. The node-js generated server doesn't match SpeckleServer structure though.

**Comment by didimitrie** [comment]
>  @didimitrie is there a way to automatically update the schema in SpeckleServer? I've got the new .yaml loaded in swagger and see the generate server button. The node-js generated server doesn't match SpeckleServer structure though.

nope :( but it's an easy manual fix 👍

**Comment by didimitrie** [comment]
fix which is actually not needed: `strict: false` means you can plop whatever in there ultimately. +💯for mongo

**Comment by mswaidan** [comment]
Thanks, I found the lines. Misunderstood the relationship b/t the yaml and
server.
