### ISSUE TITLE
Data privacy and data protection regulations

### ISSUE THREAD

**Issue by teocomi** [speckleworks/SpeckleCore#69]
I noticed that the Add User component exposes full email addresses. 

![image](https://user-images.githubusercontent.com/2679513/38862743-a1a3381a-422d-11e8-80aa-ad7a433b1f51.png)

I know this is nasty stuff, but given that users don't have to accept any T&C to use the service and that a [new regulation on data protection](https://www.eugdpr.org/) will soon take effect in the EU, I think we should be careful with user data.

**Comment by didimitrie** [comment]
yeps, you're right; we should switch to just a fuzzy search by name + surname.

**Comment by didimitrie** [comment]
i'm actually going to close this one as it's for the server, nothing to do with speckle core. opened a new one where it belongs: https://github.com/speckleworks/SpeckleServer/issues/74
