### ISSUE TITLE
Add Scaling support for Speckle objects

### ISSUE THREAD

**Issue by didimitrie** [speckleworks/SpeckleCore#74]
Step 0: 
- [x] I've  read the [contribution guidelines](https://github.com/speckleworks/SpeckleOrg/blob/master/CONTRIBUTING.md)!

In progress. Every speckle object will have a `.Scale( double factor )` method that will make unit conversions easier at a pre-geometry level. 

This will not work for breps though.

**Comment by Eckart-S** [comment]
Oh why does it not work for Breps?

**Comment by didimitrie** [comment]
because breps are stored as 3dm archives at the moment, so  you need to deserialise them first

**Comment by Eckart-S** [comment]
Ah ok, right... it was stored as opennurbs. No problem then.

**Comment by didimitrie** [comment]
This has now made its way in the core. SpeckleObjects have a `.Scale(double factor)` method. It's not tested much @Eckart-S, so beware!
